# Generated by Django 4.2.25 on 2025-10-21 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('uuid', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Acta')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('docente_asignado', models.EmailField(max_length=254, verbose_name='Email del Docente Asignado')),
                ('nombre_docente', models.CharField(max_length=100, verbose_name='Nombre del Docente')),
                ('codigo_sector', models.CharField(max_length=10, verbose_name='Código de Sector')),
                ('numero_revision', models.IntegerField(default=0, verbose_name='Número de Revisión')),
                ('uuid_acta_previa', models.UUIDField(blank=True, null=True, verbose_name='UUID Acta Previa')),
                ('estado', models.CharField(choices=[('recibida', 'Recibida'), ('pendiente_otp', 'Pendiente Firma OTP'), ('pendiente_blockchain', 'Pendiente Blockchain'), ('firmada', 'Firmada'), ('fallo_blockchain', 'Fallo en Blockchain'), ('rechazada', 'Rechazada')], default='recibida', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('fecha_firma', models.DateField(blank=True, null=True, verbose_name='Fecha de Firma')),
                ('fecha_rechazo', models.DateField(blank=True, null=True, verbose_name='Fecha de Rechazo')),
                ('motivo_rechazo', models.TextField(blank=True, null=True, verbose_name='Motivo de Rechazo')),
                ('firmada_con_otp', models.BooleanField(default=False, verbose_name='Firmada con OTP')),
                ('registro_blockchain', models.CharField(blank=True, max_length=20, null=True, verbose_name='Registro en Blockchain')),
                ('hash_documento', models.CharField(blank=True, max_length=64, null=True, verbose_name='Hash del Documento')),
                ('ip_firma', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de Firma')),
                ('latitud', models.FloatField(blank=True, null=True, verbose_name='Latitud')),
                ('longitud', models.FloatField(blank=True, null=True, verbose_name='Longitud')),
                ('precision_gps', models.CharField(blank=True, max_length=50, null=True, verbose_name='Precisión GPS')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'Acta',
                'verbose_name_plural': 'Actas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
