# Generated by Django 4.2.25 on 2025-10-22 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acta',
            name='codigo_sector',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='El código de sector debe ser un número de 3 dígitos', regex='^\\d{3}$')], verbose_name='Código de Sector'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='docente_asignado',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Ingrese un email válido')], verbose_name='Email del Docente Asignado'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='nombre_docente',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='El nombre solo puede contener letras, espacios y puntos', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s\\.]+$')], verbose_name='Nombre del Docente'),
        ),
    ]
