# Generated by Django 4.2.25 on 2025-12-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0002_alter_acta_codigo_sector_alter_acta_docente_asignado_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='acta',
            index=models.Index(fields=['estado', 'activa'], name='acta_estado_activa_idx'),
        ),
        migrations.AddIndex(
            model_name='acta',
            index=models.Index(fields=['docente_asignado'], name='acta_docente_idx'),
        ),
        migrations.AddIndex(
            model_name='acta',
            index=models.Index(fields=['fecha_creacion'], name='acta_fecha_creacion_idx'),
        ),
        migrations.AddIndex(
            model_name='acta',
            index=models.Index(fields=['fecha_firma'], name='acta_fecha_firma_idx'),
        ),
        migrations.AddIndex(
            model_name='acta',
            index=models.Index(fields=['uuid_acta_previa'], name='acta_uuid_previa_idx'),
        ),
    ]
