# Generated by Django 4.2.25 on 2025-10-22 12:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('estado', models.CharField(default='recibida', max_length=50)),
                ('doctype', models.CharField(default='acta', max_length=50)),
                ('life_cycle_state', models.CharField(default='recibida', max_length=50)),
                ('filename', models.CharField(default='documento.pdf', max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('removed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'file_file',
                'managed': True,
            },
        ),
    ]
