# Generated by Django 5.2.7 on 2025-10-31 17:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_add_mock_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='TituloFile',
            fields=[
            ],
            options={
                'verbose_name': 'Título',
                'verbose_name_plural': 'Títulos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('model.file',),
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'managed': True, 'ordering': ['-created_at'], 'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
        migrations.AlterField(
            model_name='file',
            name='life_cycle_state_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
