# Generated by Django 4.2.25 on 2025-12-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_titulofile_alter_file_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['doctype_legacy', 'estado'], name='file_doctype_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['doctype_obj', 'life_cycle_state_obj'], name='file_doctype_state_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['created_at'], name='file_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['updated_at'], name='file_updated_at_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['removed'], name='file_removed_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['serie'], name='file_serie_idx'),
        ),
    ]
